client_config_backend: settings
client_config:
  client_id: 893516516445-ejnis71kr3bour4123lo4c5eis1jq62f.apps.googleusercontent.com
  client_secret: 93kT-0mXKqDoOHkbcbbOCqhw

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install
